title: "Fullstack Javascript Slides" # the name of your site, e.g. ACME Corp.
intro: 
  background-image-path: "https://res.cloudinary.com/boolean-spa/image/upload/v1621317790/boolean-fullstack-js/Intro-stretch_rtm31d.svg"
  title: "Aplicación web"
  subtitle: "Fullstack Javascript"